coverage:
  status:
    project:
      default: off
      minimum:
        target: 70%
      decrement:
        target: auto
        threshold: 0.5%
        if_not_found: success
      loquacious:
        target: 70%
        flags: loquacious
      locales:
        target: 70%
        flags: locales
    patch:
      default: off
      pr_coverage:
        target: 70%
flags:
  loquacious:
    paths:
      - loquacious/src/main/java/com/saantiaguilera/loquacious
flags:
  locales:
    paths:
      - locales/src/main/java/com/saantiaguilera/locales
comment:
  layout: "diff, flags"
  behavior: default
  require_changes: false
  require_base: no
  require_head: no
  branches: null